
# waybar & wmenu required.
bind=SUPER,x,spawn,ghostty
bind=SUPER,b,spawn, firefox
bind=SUPER+SHIFT,a,spawn, bash -c 'pgrep rofi && pkill rofi || rofi -show drun'
bind=SUPER,1,comboview,1
bind=SUPER,2,comboview,2
bind=SUPER,3,comboview,3
bind=SUPER,4,comboview,4
bind=SUPER,5,comboview,5
bind=SUPER,6,comboview,6
bind=SUPER,7,comboview,7
bind=SUPER,8,comboview,8
bind=SUPER,9,comboview,9

bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

bind=SUPER,q,killclient
bind=SUPER+SHIFT,r,reload_config
bind=SUPER,y,spawn, ghostty -e yazi
#bind=SUPER,d,spawn, ghostty -e concord
bind=SUPER,d,spawn, ghostty -e endcord
bind=SUPER,e,spawn, ghostty -e aerc
bind=SUPER+SHIFT,d,spawn,  dbus-run-session flatpak run com.discordapp.Discord
bind=SUPER+SHIFT,b,spawn, blender
bind=SUPER+SHIFT,l,spawn, sh -c 'quickshell --config lockscreen'
bind=SUPER,v,spawn, quickshell -c bar ipc call clipboard toggleClipboard
bind=SUPER,a,spawn,quickshell -c bar ipc call launcher toggleLauncher
bind=SUPER,n,spawn, wlsunset -T 6500 -t 4000 -S 00:00 -s 00:01
bind=SUPER+SHIFT,n,spawn, pkill wlsunset
bind=SUPER,c,spawn, npm --prefix ~/Lost/Programming/Rust/Tauri/Lumus run tauri dev
bind=SUPER+SHIFT,c,spawn,firejail --net=none wine ~/.wine/drive_c/"Program Files"/"Cisco Packet Tracer 8.2.2"/bin/PacketTracer.exe
bind=SUPER,w,spawn, ~/Applications/wooz
bind=SUPER,g,spawn, sh -c 'pgrep -x gsr-ui >/dev/null && pkill -x gsr-ui || gsr-ui'
bind=SUPER+SHIFT,g,spawn, ~/dotfiles/Scripts/copy-ss.sh

#loginctl commands
bind=CTRL+SHIFT,r,spawn, loginctl reboot
bind=SUPER,Escape, spawn, loginctl poweroff
bind=SUPER+SHIFT,q, spawn, loginctl terminate-session self

# Layouts
bind=SUPER+SHIFT,t,setlayout,tile
bind=SUPER+SHIFT,s,setlayout,scroller
bind=SUPER+SHIFT,v,setlayout,vertical_scroller
#bind=SUPER+SHIFT,n,switch_layout

#Resize
#keymode=resize
#bind=NONE, Bottom, resizewin,

# Screenshots
#bind=NONE,Print,spawn,sh -c 'grim -g "$(slurp)" - | wl-copy --type image/png'
#
#bind=ALT,Print,spawn,sh -c 'grim -o eDP-1 - | wl-copy --type image/png'
#
bind=ALT,Print,spawn,sh -c 'grim -g "$(slurp)" - | satty --filename -'
#
#bind=SUPER,Print,spawn,sh -c 'grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +%F_%H-%M-%S).png'

#Audio and brightness
bindl = None, XF86AudioRaiseVolume, spawn, pamixer -i 10 
bindl = None, XF86AudioLowerVolume, spawn, pamixer -d 10
bindl = None, XF86AudioMicMute, spawn, pamixer --default-source -m
bindl = None, XF86AudioMute, spawn, pamixer -t

bindl = None, XF86MonBrightnessUp, spawn, brightnessctl s +5%
bindl = None, XF86MonBrightnessDown, spawn, brightnessctl s 5%-
bindl = None, F12, spawn, brightnessctl s +5%
bindl = None, F11, spawn, brightnessctl s 5%-

bind=SUPER,f,togglefullscreen,
bind=SUPER,Space,togglefloating,

# smartmovewin
bind=CTRL+SHIFT,k,smartmovewin,up
bind=CTRL+SHIFT,j,smartmovewin,down
bind=CTRL+SHIFT,h,smartmovewin,left
bind=CTRL+SHIFT,l,smartmovewin,right

# switch window focus
bind=SUPER,j,focusstack,next
bind=SUPER,k,focusstack,prev
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right

# swap window
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

