[theme]
format_message = "[%timestamp] <%global_name> | %content %edited"
format_message_grouped = "                     > %content %edited"
format_newline = "                       %content"
format_reply = "[REPLY] <%global_name> | ┌──🡲 [%timestamp] %content"
format_reactions = "[REACT]                └──⤙ %reactions"
format_reactions_newline = "[REACT]                     %reactions"
format_interaction = "                       ┌──⤙ %global_name used [%command]"
smart_chat_lines = Flase
dynamic_name_len = False

color_format_message = [[250, -2], [245, -2, 0, 0, 7], [242, -2, 0, 8, 9], [242, -2, 0, 19, 20], [255, -2, 0, 21, 22]]
color_format_message_grouped = [[-1, -1], [245, -2, 0, 21, 22]]
color_format_newline = None

color_format_reply = [[245, -2], [240, -2, 0, 0, 7], [238, -2, 0, 8, 9], [235, -2, 0, 19, 20], [-1, -2, 0, 21, 27]]

color_format_reactions = [[245, -2], [230, -2, 0, 0, 7], [-1, -2, 0, 23, 27]]

color_format_interaction = [[245, -2], [220, -2, 0, 0, 7], [-1, -2, 0, 21, 27]]

color_format_forum = [[-1, -2], [240, -2, 0, 0, 12], [238, -2, 0, 15, 20]]

# ===== Tree Colors =====

# Normal channels/servers
color_tree_default = [245, -2]

# Currently selected item (cursor)
color_tree_selected = [0, 245]

# Muted channels
color_tree_muted = [245, -2]

# Active channel
color_tree_active = [238, -2]

# Unread channels (bright + bold)
color_tree_unseen = [255, -2, "b"]

# Channels with mentions
color_tree_mentioned = [250, -2]

# Active channel that also has mentions
color_tree_active_mentioned = [255, 238]

tree_drop_down_intersect = "├"
tree_drop_down_corner = "└"
tree_drop_down_pointer = ">"
tree_drop_down_thread = "<"
border_corners = "┌└┐┘"
