[mgr]
cwd = { fg = "#d0d0d0" }
hovered         = { fg = "#080808", bg = "#b8b8b8" }
preview_hovered = { fg = "#080808", bg = "#8f8f8f" }
find_keyword    = { fg = "#080808", bg = "#d0d0d0", bold = true }
find_position   = { fg = "#d0d0d0", bold = true }
marker_copied   = { fg = "#b8b8b8", bg = "#b8b8b8" }
marker_cut      = { fg = "#4a0f0f", bg = "#4a0f0f" }
marker_selected = { fg = "#8f8f8f", bg = "#8f8f8f" }
tab_active      = { fg = "#080808", bg = "#b8b8b8", bold = true }
tab_inactive    = { fg = "#606060", bg = "#161616" }
border_symbol   = "│"
border_style    = { fg = "#383838" }

[status]
separator_open  = ""
separator_close = ""
progress_label  = { fg = "#d0d0d0", bold = true }
progress_normal = { fg = "#8f8f8f", bg = "#161616" }
progress_error  = { fg = "#4a0f0f", bg = "#161616" }

[select]
border   = { fg = "#8f8f8f" }
active   = { fg = "#b8b8b8", bold = true }
inactive = {}

[input]
border   = { fg = "#8f8f8f" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "#383838" }
active   = { bg = "#202020" }
inactive = {}

[icon]
conds = [
    { if = "dir", text = "", fg = "#b8b8b8" },
    { if = "file", text = "", fg = "#b8b8b8" },
]

dirs = [
    { name = "Desktop",   text = "", fg = "#b8b8b8" },
    { name = "Documents", text = "", fg = "#b8b8b8" },
    { name = "Downloads", text = "", fg = "#b8b8b8" },
    { name = "Public",    text = "", fg = "#b8b8b8" },
    { name = "Pictures",  text = "", fg = "#b8b8b8" },
    { name = "Music",     text = "", fg = "#b8b8b8" },
    { name = "Videos",    text = "", fg = "#b8b8b8" },
]

[tasks]
border  = { fg = "#383838" }
title   = { fg = "#b8b8b8", bold = true }
hovered = { fg = "#080808", bg = "#b8b8b8" }

[which]
cols            = 3
mask            = { bg = "#080808" }
cand            = { fg = "#b8b8b8" }
rest            = { fg = "#606060" }
desc            = { fg = "#d0d0d0" }
separator       = " ➜ "
separator_style = { fg = "#383838" }

[help]
on      = { fg = "#d0d0d0" }
exec    = { fg = "#b8b8b8" }
desc    = { fg = "#d0d0d0" }
hovered = { bg = "#202020", bold = true }
footer  = { fg = "#080808", bg = "#b8b8b8" }

[filetype]
rules = [
    { mime = "image/*",          fg = "#d0d0d0" },
    { mime = "video/*",          fg = "#8f8f8f" },
    { mime = "audio/*",          fg = "#b8b8b8" },
    { mime = "application/pdf",  fg = "#d0d0d0" },
    { mime = "application/json", fg = "#b8b8b8" },
    { mime = "*/javascript",     fg = "#b8b8b8" },
    { mime = "*/python",         fg = "#8f8f8f" },
    { mime = "*/html",           fg = "#d0d0d0" },
    { mime = "*/css",            fg = "#b8b8b8" },
    { url = "*/",                fg = "#686868", bold = true },
    { url = "*",                 fg = "#b8b8b8" },
]
