[personal]
source        = imaps://namanuzumaki13%40gmail.com:rumu%20curz%20zcle%20cqba@imap.gmail.com:993
outgoing      = smtps://namanuzumaki13%40gmail.com:rumu%20curz%20zcle%20cqba@smtp.gmail.com:465
default       = INBOX
from          = naman <namanuzumaki13@gmail.com>
copy-to       = ~/Lost/Gmail/uzu
cache-headers = true

[school]
source = imaps://080bei025.naman%40pcampus.edu.np:cmgz%20bxth%20qwdj%20ixey@imap.gmail.com:993
outgoing      = smtps://080bei025.naman%40pcampus.edu.np:cmgz%20bxth%20qwdj%20ixey@smtp.gmail.com:465
default       = INBOX
from          = Naman <080bei025.naman@pcampus.edu.np>
copy-to       = ~/Lost/Gmail/school
cache-headers = true


[professional]
source = imaps://adhikarinaman00%40gmail.com:wllg%20ghgy%20pscq%20bira@imap.gmail.com:993
outgoing      = smtps://adhikarinaman00%40gmail.com:wllg%20ghgy%20pscq%20bira@smtp.gmail.com:465
default       = INBOX
from          = Naman <080bei025.naman@pcampus.edu.np>
copy-to       = ~/Lost/Gmail/professional
cache-headers = true
